#include "save_load.h"
#include <stdio.h>
#include <stdlib.h>
#include "data.h"
#include "print.h"

void save_game(const char* filename, UNIT* army1, int count1, UNIT* army2, int count2) { //Save
    FILE* f = fopen(filename, "w");
    if (!f) return;

    fprintf(f, "%d %d\n", count1, count2);
    for (int i = 0; i < count1; i++) {
        int id1 = army1[i].item1 - items;
        int id2 = army1[i].item2 ? (army1[i].item2 - items) : -1;
        fprintf(f, "%s %d %d %d\n", army1[i].name, army1[i].hp, id1, id2);
    }
    for (int i = 0; i < count2; i++) {
        int id1 = army2[i].item1 - items;
        int id2 = army2[i].item2 ? (army2[i].item2 - items) : -1;
        fprintf(f, "%s %d %d %d\n", army2[i].name, army2[i].hp, id1, id2);
    }

    fclose(f);
}

// NOTE: fscanf is safe here because input file is always generated by the game itself.

UNIT* load_game(const char* filename, int* count1, int* count2, UNIT** army2_out) { //Load
    FILE* f = fopen(filename, "r");
    if (!f) return NULL;

    fscanf(f, "%d %d", count1, count2);
    UNIT* army1 = malloc(sizeof(UNIT) * (*count1));
    UNIT* army2 = malloc(sizeof(UNIT) * (*count2));
    if (!army1 || !army2) {
        fclose(f);
        return NULL;
    }

    for (int i = 0; i < *count1; i++) { //Scanning the file for name hp and items for 1st army
        int id1, id2;
        fscanf(f, "%s %d %d %d", army1[i].name, &army1[i].hp, &id1, &id2);
        army1[i].item1 = &items[id1];
        army1[i].item2 = (id2 >= 0) ? &items[id2] : NULL;
        army1[i].y = i;
        for (int k = 0; k < SPRITE_HEIGHT; k++)
            army1[i].sprite[k] = default_sprite[k];
    }

    for (int i = 0; i < *count2; i++) { //Scanning the file for name hp and items for 2nd army
        int id1, id2;
        fscanf(f, "%s %d %d %d", army2[i].name, &army2[i].hp, &id1, &id2);
        army2[i].item1 = &items[id1];
        army2[i].item2 = (id2 >= 0) ? &items[id2] : NULL;
        army2[i].y = i;
        for (int k = 0; k < SPRITE_HEIGHT; k++)
            army2[i].sprite[k] = default_sprite[k];
    }

    fclose(f);
    *army2_out = army2;
    return army1;
}
